#include "../dockswipe27.h"
#include <cassert>
#include <cstdio>
#include <dlfcn.h>
static CGEventRef sample(uint32_t phase,double progress,double vx,uint32_t motion=1,double vy=0){auto e=CGEventCreate(nullptr);CGEventSetType(e,(CGEventType)30);CGEventSetIntegerValueField(e,(CGEventField)110,23);CGEventSetIntegerValueField(e,(CGEventField)132,phase);CGEventSetIntegerValueField(e,(CGEventField)123,motion);CGEventSetDoubleValueField(e,(CGEventField)124,progress);CGEventSetDoubleValueField(e,(CGEventField)129,vx);CGEventSetDoubleValueField(e,(CGEventField)130,vy);return e;}
int main(){uint32_t phases[]={1,2,4,8};for(uint32_t p:phases){auto e=sample(p,-.75,42);AirDockSwipe27Fields f{};assert(air_dockswipe27_decode(e,&f));assert(f.phase==p&&f.motion==1&&f.progress==-.75&&f.velocity==42);CFRelease(e);}auto bad=sample(16,0,0);AirDockSwipe27Fields f{};assert(!air_dockswipe27_decode(bad,&f));CFRelease(bad);bad=sample(2,17,0);assert(!air_dockswipe27_decode(bad,&f));CFRelease(bad);bad=sample(2,0,NAN);assert(!air_dockswipe27_decode(bad,&f));CFRelease(bad);bad=sample(2,0,INFINITY);assert(!air_dockswipe27_decode(bad,&f));CFRelease(bad);
 if(air_dockswipe27_available()){
  void *cg=dlopen("/System/Library/Frameworks/CoreGraphics.framework/CoreGraphics",RTLD_LAZY),*io=dlopen("/System/Library/Frameworks/IOKit.framework/IOKit",RTLD_LAZY);
  auto copy=(CFTypeRef(*)(CGEventRef))dlsym(cg,"CGEventCopyIOHIDEvent");auto type=(uint32_t(*)(CFTypeRef))dlsym(io,"IOHIDEventGetType");auto phase=(uint32_t(*)(CFTypeRef))dlsym(io,"IOHIDEventGetPhase");auto integer=(CFIndex(*)(CFTypeRef,uint32_t))dlsym(io,"IOHIDEventGetIntegerValue");auto floating=(double(*)(CFTypeRef,uint32_t))dlsym(io,"IOHIDEventGetFloatValue");auto children=(CFArrayRef(*)(CFTypeRef))dlsym(io,"IOHIDEventGetChildren");assert(copy&&type&&phase&&integer&&floating&&children);
  uint32_t orphanPhases[]={2,4,8};for(uint32_t p:orphanPhases){auto orphan=sample(p,.1,0);assert(!air_dockswipe27_convert(orphan,1));CFRelease(orphan);}assert(!air_dockswipe27_cancel(2));
  auto begin=sample(1,.1,0),change=sample(2,.25,0),end=sample(4,.5,37);auto began=air_dockswipe27_convert(begin,3),changed=air_dockswipe27_convert(change,4),ended=air_dockswipe27_convert(end,5);assert(began&&changed&&ended&&!air_dockswipe27_cancel(6));CFRelease(began);CFRelease(changed);CFRelease(ended);CFRelease(begin);CFRelease(change);CFRelease(end);
  begin=sample(1,.1,0);began=air_dockswipe27_convert(begin,7);assert(began);auto doubleBegin=sample(1,.2,0);assert(!air_dockswipe27_convert(doubleBegin,8));auto wrongMotion=sample(2,.2,0,2,4);assert(!air_dockswipe27_convert(wrongMotion,9));auto cancel=air_dockswipe27_cancel(10);assert(cancel&&!air_dockswipe27_cancel(11));CFRelease(cancel);CFRelease(wrongMotion);CFRelease(doubleBegin);CFRelease(began);CFRelease(begin);
  begin=sample(1,.1,0,2,0);began=air_dockswipe27_convert(begin,12);auto verticalEnd=sample(4,.4,3,2,41);auto converted=air_dockswipe27_convert(verticalEnd,13);assert(began&&converted);auto hid=copy(converted);assert(hid&&type(hid)==23&&phase(hid)==4);auto kids=children(hid);assert(kids&&CFArrayGetCount(kids)==1);auto velocity=(CFTypeRef)CFArrayGetValueAtIndex(kids,0);assert(floating(velocity,(9u<<16)|0)==41&&floating(velocity,(9u<<16)|1)==41&&floating(velocity,(9u<<16)|2)==0);CFRelease(hid);CFRelease(converted);CFRelease(verticalEnd);CFRelease(began);CFRelease(begin);
 }
 printf("PASS available=%d\n",air_dockswipe27_available());}
