#define AIR_SPACES_JOURNAL_TEST 1
#include "../spaces.mm"
#include <cassert>
#include <map>
#include <cstdio>
extern "C" void air_set_error(const char*s){if(s&&*s)fprintf(stderr,"ERR:%s\n",s);} extern "C" int air_display_restore(){return 0;}
static NSMutableDictionary *bi=nil,*ex=nil;static std::map<uint32_t,bool> fs;static std::map<uint32_t,uint64_t> mem;static int conn(){return 7;}static CFArrayRef man(int){return nullptr;}static int typ(int,uint64_t s){return s>=800?4:0;}static CFArrayRef memberships(int,int,CFArrayRef){return nullptr;}static AXError ax(AXUIElementRef,CGWindowID*){return kAXErrorFailure;}
static bool closed=false;static int ws(const SavedWindow&){return (int)(closed?WindowState::Gone:WindowState::Ready);}static int fstate(const SavedWindow&w){return fs[w.id]?1:0;}static bool setfs(const SavedWindow&w,bool d){fs[w.id]=d;if(d){mem[w.id]=w.id==101?901:902;ex[@"Current Space"]=@{@"id64":@(mem[w.id])};}return true;}static uint32_t resolve(const SavedWindow&w){return w.id;}static uint64_t ord(const SavedWindow&w){return fs[w.id]?0:mem[w.id];}static uint64_t fsid(const SavedWindow&w){return fs[w.id]?mem[w.id]:0;}static bool fmem(const SavedWindow&w){return fs[w.id];}static bool frame(const SavedWindow&w,CGRect*f){*f=CGRectMake(w.id,20,800,700);return true;}static bool move(uint32_t w,uint64_t s){mem[w]=s;return true;}static bool setframe(const SavedWindow&){return true;}static bool display(uint32_t,const std::string&u){return u=="external";}static bool sw(const std::string&u,uint64_t s){if(u!="external")return false;ex[@"Current Space"]=@{@"id64":@(s)};return true;}static bool swbi(uint64_t s){bi[@"Current Space"]=@{@"id64":@(s)};return true;}static int mission(){return (int)MissionState::Absent;}static bool topology(std::vector<std::string>&v,const std::string&,bool&o){v={"builtin","external"};o=true;return true;}
int main(){@autoreleasepool{NSString*p=[NSTemporaryDirectory() stringByAppendingPathComponent:@"air-full-v8-XXXXXX"];std::string q=p.fileSystemRepresentation;std::vector<char>d(q.begin(),q.end());d.push_back(0);assert(mkdtemp(d.data()));NSString*folder=[NSString stringWithUTF8String:d.data()];journalTestPath=[folder stringByAppendingPathComponent:@"recovery.json"];
bi=[@{@"Display Identifier":@"builtin",@"Current Space":@{@"id64":@189},@"Spaces":@[@{@"id64":@189,@"type":@0}]}mutableCopy];ex=[@{@"Display Identifier":@"external",@"Current Space":@{@"id64":@192},@"Spaces":@[@{@"id64":@189,@"type":@0},@{@"id64":@191,@"type":@0},@{@"id64":@192,@"type":@0},@{@"id64":@801,@"type":@4},@{@"id64":@802,@"type":@4},@{@"id64":@901,@"type":@4},@{@"id64":@902,@"type":@4}]}mutableCopy];RecoveryHooks h={};h.inventory=@[bi,ex];h.windowState=ws;h.fullScreenState=fstate;h.setFullScreen=setfs;h.resolveWindow=resolve;h.ordinaryAfterExit=ord;h.fullScreenMembership=fmem;h.fullScreenSpaceID=fsid;h.afterExitFrame=frame;h.move=move;h.frame=setframe;h.windowDisplay=display;h.switchDisplaySpace=sw;h.switchSpace=swbi;h.missionState=mission;h.onlineTopology=topology;recoveryHooks=&h;Api&a=api();a.conn=conn;a.managed=man;a.spaceType=typ;a.windowSpaces=memberships;a.axWindow=ax;
SavedWindow x={101,10,"a","a",CGRectMake(1,1,500,400),CGRectMake(-1000,0,1000,800),1,191,1,"external",true};x.fullScreen=true;x.fullScreenPhase=2;x.fullScreenSpace=801;x.axIdentifier="a";SavedWindow y=x;y.id=102;y.pid=11;y.bundle="b";y.space=192;y.fullScreenSpace=802;y.axIdentifier="b";saved={x,y};initialSelections={{"builtin",189,0,-1,189},{"external",189,0,-1,192}};builtinUUID="builtin";initialSpace=189;initialFullScreenIndex=-1;initialFullScreenSpace=0;finalSelectionPending=false;selectionPending={};createdSpaces.clear();ownedSpaces.clear();pendingCreate=false;pendingCreateBefore.clear();lastSelectedSpace=0;slots[0]=slots[1]=slots[2]=0;fs[101]=fs[102]=false;mem[101]=191;mem[102]=192;assert(persist());saved.clear();initialSelections.clear();assert(loadJournal());assert(restoreLocked()==0);assert(saved.empty());assert([ex[@"Current Space"][@"id64"] unsignedLongLongValue]==189);assert(![[NSFileManager defaultManager] fileExistsAtPath:journalTestPath]);
x.space=801;x.fullScreenPhase=1;saved={x};initialSelections={{"builtin",189,0,-1,189},{"external",189,0,-1,801}};builtinUUID="builtin";initialSpace=189;selectionPending={};fs[101]=true;mem[101]=801;ex[@"Current Space"]=@{@"id64":@801};assert(persist());saved.clear();initialSelections.clear();assert(loadJournal());assert(restoreLocked()==0);assert([ex[@"Current Space"][@"id64"] unsignedLongLongValue]==189);
x.fullScreenPhase=4;saved={x};builtinUUID="builtin";initialSpace=189;initialFullScreenIndex=-1;initialFullScreenSpace=0;initialSelections={{"builtin",189,0,-1,189},{"external",189,0,-1,901}};selectionPending={};fs[101]=true;mem[101]=901;ex[@"Current Space"]=@{@"id64":@901};assert(persist());saved.clear();initialSelections.clear();assert(loadJournal());assert(saved[0].fullScreenSpace==801&&saved[0].fullScreenPhase==4);assert(restoreLocked()==0);assert([ex[@"Current Space"][@"id64"] unsignedLongLongValue]==189);
// If the user closes an originally selected full-screen window, its Space
// disappears.  Recovery selects the journaled ordinary source desktop.
x.fullScreenPhase=3;x.space=191;x.fullScreenSpace=801;saved={x};closed=true;
builtinUUID="builtin";initialSpace=189;
initialSelections={{"builtin",189,0,-1,189},{"external",801,4,0,191}};
ex[@"Current Space"]=@{@"id64":@191};assert(persist());
saved.clear();initialSelections.clear();assert(loadJournal());
assert(restoreLocked()==0 && saved.empty());
assert([ex[@"Current Space"][@"id64"] unsignedLongLongValue]==191);
closed=false;
recoveryHooks=nullptr;journalTestPath=nil;assert([[NSFileManager defaultManager]removeItemAtPath:folder error:nil]);puts("v8 full restore: distinct anchors and abort-before-exit host selection passed");}}
